services:
  - type: web
    name: api-clasificacion-incidencias
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: HF_HOME
        value: /tmp/huggingface
